### ISSUE TITLE
Option to install this addon directly without HACS?

### ISSUE THREAD

**Issue by cnieves1** [Danieldiazi/homeassistant-meteogalicia#1]
Hi,
nice work!

Is there any chance that this addon could be installed directly from Home Assistant?
I mean adding your addon repository in Home Assistant.
  https://www.home-assistant.io/addons/

I have just tried to do it but I got an "is not a valid repository" error.

Thanks in advance,

**Comment by Danieldiazi** [comment]
> "is not a valid repositor

Hi! Thanks for your kind words!

This is a integration, not an addon. At this moment,  it's possible to install only adding manually my repository on HACS. I'm trying to add this repository as a default repository in HACS in order to show in the "store" and this integration installation will be more easy. In fact, this is my recently pull request: https://github.com/hacs/default/pull/1532 to do that, I hope to get it!!

Maybe in the future I gonna try to add in into HA integrations, but now, I need to improve this integration a lot!

Have you tried to install via HACS. Everything is OK through this way?

Thanks!!!!!

**Comment by cnieves1** [comment]
Hi!
Good luck with the PR! I'm sure you'll achieve that!

Yes, everything is fine if installing using HACS. 
Despite of that, I'd love to see it in HA integrations as well, when you find the time..

Thanks for your work!!
