### ISSUE TITLE
Limit number of queries/day

### ISSUE THREAD

**Issue by vz-john** [Danieldiazi/homeassistant-meteogalicia#3]
More than 40,000 queries to servizos.meteogalicia.gal in 24 hours. Is it possible to limit the number of queries per hour/day?

**Comment by Danieldiazi** [comment]
Hi, sorry about that!
You can use scan_interval option, for instance, if you put 1800 value, sensor will poll information every 30 min  instead of the default value (I think is 30 seconds).

I've just updated Readme.md in order to add this option, because there are a lot of connections to servizos.meteogalicia.gal and it can be useful to someone. I recommend to everyone to use this option.

Once again, my apologies and I hope to have time to continue improving this integration.
